apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: sample-app
  version: v1.0.0

images:
  - name: nginx
    newTag: "1.21"
