apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production
namePrefix: prod-

resources:
- ../../base

commonLabels:
  environment: production

replicas:
- name: sample-app
  count: 5

patches:
- target:
    kind: Deployment
    name: sample-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "production"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: PRODUCTION_MODE
        value: "true"

images:
- name: nginx
  newTag: "1.21"
