apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-

resources:
- ../../base

commonLabels:
  environment: dev

patches:
- target:
    kind: Deployment
    name: sample-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "development"

images:
- name: nginx
  newTag: "alpine"
