apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

images:
- name: nginx
  newTag: "1.21-alpine"

replicas:
- name: sample-app
  count: 1

commonLabels:
  environment: dev
