apiVersion: v2
name: sample-app
description: A Helm chart for our sample application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
- name: GitOps Lab
  email: admin@gitops-lab.local
keywords:
- sample
- application
- nginx
sources:
- https://github.com/your-org/sample-app
